config:
  checkout_directory: ./code
  compose: ./config/docker-compose.yml

services:
  nginx:
    type: docker-compose

  postgres:
    type: docker-compose

  elasticsearch:
    type: local

apps:
  api:
    type: nix
    dirname: digitalmarketplace-api
    git: https://github.com/alphagov/digitalmarketplace-api
    commands:
      run: make run-all
      build: make frontend-build
    healthcheck: http://localhost:5000/_status
    order: 1
    styles:
      fg: blue
      attr: bold
