version: '2'


networks:
  dmrunner:
    driver: bridge


services:
  postgres:
    container_name: dm-postgres
    networks:
      - dmrunner
    image: "postgres:9.5"
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - DMRUNNER_USER

  elasticsearch:
    container_name: dm-elasticsearch
    networks:
      - dmrunner
    image: "elasticsearch:5.4"
    ports:
      - "9200:9200"

  nginx:
    container_name: dm-nginx
    networks:
      - dmrunner
    image: "digitalmarketplace/local-nginx:latest"
    build:
      context: ./
      dockerfile: ./nginx/local-nginx.docker
    ports:
      - "80:80"
