# This file contains mostly-static data that doesn't need to be edited by the end-user but shouldn't be embedded in
# code directly.

# The base git url used to clone repositories that need to be checked-out. If these ever end up fragmented, this needs
# moving under each 'repositories' key.
base-git-url: git@github.com:alphagov

# The path to the Docker compose files used for running services. This shouldn't need to change.
docker-compose-path: config

# The host to query when running healthchecks on apps
server: localhost

data-dump-url: https://s3.console.aws.amazon.com/s3/buckets/digitalmarketplace-cleaned-db-dumps
sql-data-path: config/sql/data

environment:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  DM_S3_ENDPOINT_PORT: 4566

# Details repositories to be downloaded, bootstrapped, and executed.
repositories:
  # Core repositories to download and run.
  digitalmarketplace-api:
    name: api
    short-name: api
    bootstrap: invoke requirements-dev run-migrations
    run-order: 1
    healthcheck:
      port: 5000
      endpoint: /_status
    commands:
      run: invoke run-app
      rebuild: invoke run-all

  digitalmarketplace-search-api:
    name: search-api
    short-name: search
    bootstrap: invoke requirements-dev
    run-order: 1
    healthcheck:
      port: 5009
      endpoint: /_status
    commands:
      run: invoke run-app
      rebuild: invoke run-all

  digitalmarketplace-admin-frontend:
    name: admin-frontend
    short-name: admin
    bootstrap: invoke requirements-dev frontend-build
    run-order: 2
    healthcheck:
      port: 5004
      endpoint: /admin/_status
    commands:
      run: invoke run-app
      rebuild: invoke run-all
      frontend: invoke frontend-build

  digitalmarketplace-brief-responses-frontend:
    name: brief-responses-frontend
    short-name: brf-resp
    bootstrap: invoke requirements-dev frontend-build
    run-order: 2
    healthcheck:
      port: 5006
      endpoint: /suppliers/opportunities/_status
    commands:
      run: invoke run-app
      rebuild: invoke run-all
      frontend: invoke frontend-build

  digitalmarketplace-briefs-frontend:
    name: briefs-frontend
    short-name: briefs
    bootstrap: invoke requirements-dev frontend-build
    run-order: 2
    healthcheck:
      port: 5005
      endpoint: /buyers/_status
    commands:
      run: invoke run-app
      rebuild: invoke run-all
      frontend: invoke frontend-build

  digitalmarketplace-buyer-frontend:
    name: buyer-frontend
    short-name: buyer
    bootstrap: invoke requirements-dev frontend-build
    run-order: 2
    healthcheck:
      port: 5002
      endpoint: /_status
    commands:
      run: invoke run-app
      rebuild: invoke run-all
      frontend: invoke frontend-build

  digitalmarketplace-supplier-frontend:
    name: supplier-frontend
    short-name: supplier
    bootstrap: invoke requirements-dev frontend-build
    run-order: 2
    healthcheck:
      port: 5003
      endpoint: /suppliers/_status
    commands:
      run: invoke run-app
      rebuild: invoke run-all
      frontend: invoke frontend-build

  digitalmarketplace-user-frontend:
    name: user-frontend
    short-name: user
    bootstrap: invoke requirements-dev frontend-build
    run-order: 2
    healthcheck:
      port: 5007
      endpoint: /user/_status
    commands:
      run: invoke run-app
      rebuild: invoke run-all
      frontend: invoke frontend-build

  # Additional repositories to download and bootstrap during setup, but aren't "run" like the rest of the apps.
  digitalmarketplace-scripts:
    name: scripts
    bootstrap: invoke requirements-dev

  digitalmarketplace-functional-tests:
    name: functional-tests

index:
  repository: digitalmarketplace-scripts
  command: venv/bin/python scripts/index-to-search-service.py
  test: http://localhost:9200/{index}

  dependencies:
    - digitalmarketplace-api
    - digitalmarketplace-search-api

  indices:
    - positional:
        - services
        - dev
      keyword:
        frameworks: g-cloud-12
        index: g-cloud-12
        create-with-mapping: services-g-cloud-12

    - positional:
        - briefs
        - dev
      keyword:
        frameworks: digital-outcomes-and-specialists-4
        index: briefs-digital-outcomes-and-specialists
        create-with-mapping: briefs-digital-outcomes-and-specialists-2
